name: publish

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  publish:
    name: Publish on npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node with latest LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run package tests
        run: npm run test

      - id: publish
        name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version updated: ${{ steps.publish.outputs.old-version }} -> ${{ steps.publish.outputs.version }}"
